# Generated by Django 3.2.18 on 2023-04-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.CharField(max_length=80)),
                ('Value', models.FloatField()),
                ('CustomerEmail', models.CharField(max_length=80)),
                ('Company', models.CharField(max_length=80)),
                ('City', models.CharField(max_length=80)),
                ('Postcode', models.CharField(max_length=80)),
                ('Country', models.CharField(max_length=80)),
                ('SourceCurrency', models.CharField(max_length=5)),
                ('SysCurrency', models.CharField(max_length=5)),
                ('Timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=80)),
                ('Salt', models.CharField(max_length=80)),
            ],
        ),
    ]
