# Generated by Django 3.2.18 on 2023-03-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('card_number', models.CharField(max_length=16)),
                ('payment_method', models.CharField(max_length=30)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('value', models.IntegerField()),
                ('payment_method', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
