# Generated by Django 3.2.18 on 2023-03-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=80),
        ),
    ]
