# Generated by Django 3.2.18 on 2023-03-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20230303_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.CharField(max_length=80)),
                ('Value', models.FloatField()),
                ('CustomerEmail', models.CharField(max_length=80)),
                ('Timestamp', models.DateTimeField()),
                ('Company', models.DateTimeField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=80)),
                ('Salt', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
