# Generated by Django 3.2.18 on 2023-03-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20230328_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
