# Generated by Django 3.2.18 on 2023-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20230328_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Company',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Timestamp',
            field=models.FloatField(),
        ),
    ]
