name: test-service

on: 
  push: 
    branches: [ 'main' ]
  pull_request: 
    branches: [ '**' ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      working-directory: ./Implementation/payfriend_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      working-directory: ./Implementation/payfriend_service
      run: |
        python manage.py test