name: test-service

on: 
  push: 
    branches: [ 'main' ]
  pull_request: 
    branches: [ '**' ]

jobs:

  test:
    runs-on: ubuntu-latest # operating system your code will run on
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      working-directory: ./Implementation/payfriend_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      working-directory: ./Implementation/payfriend_service
      run: |
        python manage.py test